//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int ID { get; set; }
        public int ID_Person { get; set; }
        public int ID_Answer { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Person Person { get; set; }
    }
}
